

defaults:
  - dataset: nyt

debug: false

seed: 7
base_model: distilgpt2
base_model_state_dict: /iris/u/nathu/un_camels/pretrained_models/nyt/distilgpt2.pt

weight_model_base: distilgpt2
weight_model_freeze_base: false
weight_model_nl: sigmoid

future_loss_weight: 0.0 #between 0 and 1, how much of the loss to be random next day doc

batch_size: 6
num_epochs: 10

reset_base_frequency: 8
gradient_accumulation_steps: 8
validation_frequency: 240 #how often we validate, in terms of model updates (batchs*gradient_accumulation_steps)

outer_lr: 2.5e-5
inner_lr: 1e-4
gradient_clip_threshold: 10

notes: ''

hydra:
  job:
    chdir: true
  run:  
    dir: outputs/metatrain/${dataset.name}/${now:%Y-%m-%d}_${now:%H:%M:%S}:${notes}
  