defaults:
  - dataset: archivalqa
  - loss_weighting: ??? #one of ['init', 'uniform', 'CaMeLS', 'salient_spans']

seed: 7
downsample_to: -1 #if -1, we use the full dataset. Otherwise, we downsample to this number of documents

lr: .0001

base_model: ???
base_model_state_dict: null

r: 4 #rank for LORA
lora_model_path: ???

adapt_with_lora: false
data_split: test #one of ['test', 'val']

optimizer: adam

max_answer_len: 24
k_generations: 1

notes: ''

hydra:
  job:
    chdir: true
  run:  
    dir:  outputs/eval/${dataset.name}-${data_split}-${downsample_to}/${base_model}/${loss_weighting.name}_${notes}_fusedLora${adapt_with_lora}/lr:${lr}_seed:${seed}_time:${now:%Y-%m-%d}_${now:%H:%M:%S}
  sweep:
    dir: outputs/eval/${dataset.name}-${data_split}-${downsample_to}/${base_model}/${loss_weighting.name}_${notes}_fusedLora${adapt_with_lora}
    subdir: lr:${lr}_seed:${seed}_time:${now:%Y-%m-%d}_${now:%H:%M:%S}
  