defaults:
  - dataset: archivalqa

seed: 7
downsample_to: -1 #if -1, we use the full dataset. Otherwise, we downsample to this number of documents

lr: .0001

base_model: ???
base_model_state_dict: null

r: 4 #rank for LORA
lora_model_path: ???

loss_weighting: ??? #one of ['init', 'uniform', 'CaMeLS', 'salient_spans']

data_split: test #one of ['test', 'val']

optimizer: adam

max_answer_len: 24
k_generations: 1

notes: ''

hydra:
  job:
    chdir: true
  run:  
    dir: outputs/eval/${dataset.name}-${data_split}/${base_model}/${loss_weighting}/lr:${lr}_seed:${seed}_${notes}_time:${now:%Y-%m-%d}_${now:%H:%M:%S}
  