defaults:
  - dataset: nyt


base_model: ??
base_model_state_dict: null
lr: 0.0001
batch_size: 8
gradient_accumulation_steps: 1
validations_per_epoch: 10
num_epochs: 20

device: cuda
gradient_checkpointing: False
optimizer: adam



hydra:
  job:
    chdir: true
  run:  
    dir: outputs/pretraining/${dataset.name}/${base_model}/${now:%Y-%m-%d}_${now:%H:%M:%S}
  